server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # Para que el iframe/web component pueda hacer fetch al back
  add_header Access-Control-Allow-Origin *;
}